[tool.poetry]
name = "authorship_tool"
version = "0.1.0"
description = ""
authors = ["ZEKE320 <46393375+ZEKE320@users.noreply.github.com>"]
readme = "README.md"
packages = [{ from = ".", include = "authorship_tool" }]

[tool.poetry.dependencies]
python = "^3.11"
black = { extras = ["jupyter"], version = "^23.12.1" }
isort = "^5.13.2"
jupyter = "*"
lightgbm = "*"
matplotlib = "*"
mypy = "^1.8.0"
nltk = "*"
numpy = "^1.26.3"
pandas = "*"
pandas-stubs = "*"
pydash = "^7.0.6"
pytest = "*"
pytest-mock = "*"
rich = "*"
scikit-learn = "*"
shap = "*"
tabulate = "*"
types-tabulate = "*"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"

[tool.mypy]
plugins = "numpy.typing.mypy_plugin"

[tool.pylint.MASTER]
disable = "wrong-import-position"

[tool.pylint."FORMAT"]
max-line-length = 88
