[tool.black]
line-length = 100

[tool.poetry]
name = "authorship_tool"
version = "0.1.0"
description = ""
authors = ["ZEKE320 <46393375+ZEKE320@users.noreply.github.com>"]
readme = "README.md"
packages = [{ include = "authorship_tool", from = "authorship_tool" }]

[tool.poetry.dependencies]
python = "^3.11"
nltk = "*"
black = { extras = ["jupyter"], version = "*" }
pandas = "*"
numpy = "*"
scikit-learn = "*"
shap = "*"
tabulate = "*"
matplotlib = "*"
mypy = "*"
ipykernel = "*"
jupyter = "*"
lightgbm = "*"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
