[tool.poetry]
name = "authorship_tool"
version = "0.1.0"
description = ""
authors = ["ZEKE320 <46393375+ZEKE320@users.noreply.github.com>"]
readme = "README.md"
packages = [{ from = ".", include = "authorship_tool" }]

[tool.poetry.dependencies]
python = "^3.11"
jupyter = "*"
lightgbm = "*"
matplotlib = "*"
nltk = "*"
numpy = "*"
pandas = "*"
pandas-stubs = "*"
scikit-learn = "*"
tabulate = "*"
types-pillow = "*"
types-psutil = "*"
types-tabulate = "*"
python-dotenv = "*"
shap = "*"
pytest = "*"
pytest-mock = "*"
rich = "*"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
